# Generated by Django 3.2 on 2021-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Shirts'), ('SW', 'Sportswear'), ('O', 'Outwear')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2, null=True),
        ),
    ]
