# Generated by Django 3.2 on 2021-05-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210501_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('iPhone', 'iPhone'), ('Samsung', 'Samsung')], max_length=20),
        ),
    ]
