# Generated by Django 3.2 on 2021-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210503_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_spltag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
