# Generated by Django 3.2 on 2021-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_item_spltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_qty',
            field=models.IntegerField(default=1),
        ),
    ]
