# Generated by Django 3.2 on 2021-05-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='street_address_address',
            new_name='street_address',
        ),
    ]
