# Generated by Django 3.2 on 2021-05-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210519_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_code',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
    ]
