# Generated by Django 3.2 on 2021-05-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210522_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='defualt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='defualt',
            field=models.BooleanField(default=False),
        ),
    ]
