# Generated by Django 3.2 on 2021-05-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210524_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='defualt',
            new_name='default',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='defualt',
            new_name='default',
        ),
    ]
